[project]
name = "testmasterbsu"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "cairosvg>=2.7.1",
    "lxml>=5.3.0",
    "pillow>=12.1.0",
    "python-docx>=1.2.0",
    "pywin32>=311",
]
